# 딥러닝을 이용한 자연어 처리 
* 인공지능 플랫폼이 갖춰야 할 필수 능력 중하나가 사람의 언어를 이해하는 것. 
* 자연어처리(Natural Language Processing, NLP)는 음성이나 텍스트를 컴퓨터가 인식하고 처리하는것.
* 컴퓨터 알고리즘은 수치로 된 데이터만 이해하기 때문에 텍스트를 정제하는 전처리 과정이 필수 

##1.텍스트의 토큰화 

In [55]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text = '해보지 않으면 해낼 수 없다.'
result = text_to_word_sequence(text)
print('토큰화 :\n',result)

토큰화 :
 ['해보지', '않으면', '해낼', '수', '없다']


* 주어인 텍스트를 단어 단위로 쉽게 나눠주는 text_to_word_sequence 함수를 사용해준다. 

In [56]:
from tensorflow.keras.preprocessing.text import Tokenizer
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']
token = Tokenizer()
token.fit_on_texts(docs)
print('단어 갯수 카운트 :\n', token.word_counts)

단어 갯수 카운트 :
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


* 케라스의 Tokenizer() 함수를 사용하면 단어의 빈도수를 쉽계 계산한다. 
* word_counts를 이용해 각 문장에서 토큰화된 단어의 빈도수를 리턴해준다. 
* 또한 OrderdDict 클래스에 담겨져 있는 상태로 리턴이 되기 때문에, 순서를 기억해준다. 

In [57]:
print('문장 갯수 카운트  :',token.document_count)

문장 갯수 카운트  : 3


* document_count() 함수에는 토큰화한 docs의 문장 개수를 리턴해준다. 

In [58]:
print('각 단어가 몇개의 문장에 포함되었는가 :\n',token.word_docs)

각 단어가 몇개의 문장에 포함되었는가 :
 defaultdict(<class 'int'>, {'나누어': 1, '텍스트의': 2, '토큰화합니다': 1, '각': 1, '단어를': 1, '먼저': 1, '인식됩니다': 1, '토큰화해야': 1, '딥러닝에서': 2, '단어로': 1, '토큰화한': 1, '사용할': 1, '결과는': 1, '있습니다': 1, '수': 1})


* 또한 word_docs() 함수를 통해 각 단어들이 몇개의 문장에 나오는가를 세어서 출력한다. (문장별 단어의 빈도수를 보여줌)

In [59]:
print('각 단어에 매겨진 인덱스 값 :\n',token.word_index)

각 단어에 매겨진 인덱스 값 :
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


* 각 단어에 매겨진 인덱스 값을 출력하려면 word_index()함수를 사용하면 된다. 

## 2.단어의 원-핫 인코딩

* 단어가 문장의 다른요소와 어떤 관계를 가지고 있는지 알아보는 방법이 필요하다.
* 이러한 기법중 가장 기본적인 방법이 원-핫 인코딩(one-hot-encoding)
* 어떤 문장을 토큰화 하고, 각 토큰이 배열네에서 해당하는 위치를 1로 바꿔서 백터와 하는 방법

In [60]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다.'
result = text_to_word_sequence(text)
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


* 토큰화 함수를 불러와 단어 단위로 토큰화 하고, 각 단어의 인덱스 값을 출력

In [61]:
x = token.texts_to_sequences([text])
x

[[1, 2, 3, 4, 5, 6]]

* text_to_sequences() 함수를 이용해 앞서 만들어진 토큰의 인덱스로만 채워진 배열을 만들어준다. 
* 이제 1~6까지의 정수로 인덱스 되어 있는 것을 0과 1로만 이루어진 배열로 바꿔주는 to_categorical()함수를 사용해 원-핫 인코딩 과정을 진행한다.
* 배열의 가장앞에 0이 추가되므로, 단어 수보다 1이 더 많게 인덱스 숫자를 잡아주는 것에 유의한다. 

In [62]:
from keras.utils import to_categorical

#인덱스 수에 하나를 추가해서 원-핫 인코딩 배열만들기 
word_size = len(token.word_index) +1
x = to_categorical(x, num_classes = word_size)
for i in range(len(x[0])):
  print(x[0][i], result[i])

[0. 1. 0. 0. 0. 0. 0.] 오랫동안
[0. 0. 1. 0. 0. 0. 0.] 꿈꾸는
[0. 0. 0. 1. 0. 0. 0.] 이는
[0. 0. 0. 0. 1. 0. 0.] 그
[0. 0. 0. 0. 0. 1. 0.] 꿈을
[0. 0. 0. 0. 0. 0. 1.] 닮아간다


## 3.단어 임베딩 
* 원-핫 인코딩을 그대로 들고가기에는 벡터의 길이가  너무 길어지기 때문에, 공간적 낭비를 해결하기위해 단어 임베딩(Word embedding)을 해준다. 
* 단어 임베딩은 주어진 배열을 정해진 길이로 압축 시켜준다. 
* 단어간의 유사도를 계산하여 압축시켜주는 원리로, 적절한 크기의 배열로 바꿔주기 최적의 유사도를 계산하는 학습과정을 거친다. 
* 이때 등장하는것이 바로 오차역전파. 이러한 과정은 Embedding()함수를 사용해 간단히 해낼 수 있다. 

In [63]:
from keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Embedding(16,4))

TypeError: ignored

* Embedding() 함수는 최소 2개의 매개변수를 필요로 한다. 입력, 출력, 위의 문구 는 16개의 입력단어를 임베딩후, 출력되는 벡터크기를 4로 한다는 것이다. 

## 4.텍스트를 읽고 긍정, 부정 예측하기 
* 영화를 보고 남긴 리뷰를 딥러닝 모델로 학습하여, 각 리뷰가 긍적적이면 1, 부정적이면 0이라는 클래스로 예측해보자. 

In [64]:
from numpy import array
docs = ['너무 재밌네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한번 더 보고 싶네요',
        '글쎄요', '별로에요','생각보다 지루하네요', '연기가 어색해요','재미없어요']

classes = array([1,1,1,1,1,0,0,0,0,0])
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고': 13, '싶네요': 14, '글쎄요': 15, '별로에요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [65]:
x = token.texts_to_sequences(docs) #토큰에 지정된 인덱스로 새로운 배열 생성
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


* 각 단어가 1부터 20까지의 숫자로 토큰화 되었다는 것을 알 수 있다. 입력된 리뷰 데이터의 토큰 수가 각각 다르다.
* 즉, '최고에요'라는 단어는 하나의 단어로 인식되어, 인덱스가 하나만 존재하는 토큰인 반면에, '참 잘 만든 영화에요'는 네개의 단어으로 인식되어 인덱스가 4개인 토큰으로 저장된다. 
* 딥러닝 모델에 입력을 하기 위해선 학습 데이터의 길이가 동일해야 된다.
* 이렇게 길이를 똑같이 맞춰 주는 작업을 padding이라고 한다.  

### 텍스트 패딩(Padding)

In [66]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_x = pad_sequences(x,4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


* 케라스에서 제공하는 pad_sequences() 함수를 통해, 인덱스별로 구별되어 토큰화 되어 저장된 단어 배열을 넘겨주어 x별의 길이를 4로 맞춰주어, 모든 입력데이터에 대해 길이를 동일화하는 padding작업을 해줄 수 있다. 

### 입력될 단어들의 긍정, 부정 정도를, 단어임베딩을 포함하여 결과를 출력해보기. 
* 임베딩 함수에 필요한 세가지 파라미터는 '입력','출력', 단어 수 이다. 

In [70]:
from tensorflow.keras.layers import Dense, Flatten, Embedding
from numpy import array
import tensorflow as tf
word_size = len(token.word_index) +1

model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4)) #입력 될 단어수는 우리는 padding과정을 거쳐 각 문장당 4개의 입력으로 분할
model.add(Flatten()) # Flatten()함수를 사용해 2차원 배열을 1차원으로 바꿔준다.
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer= 'adam', metrics = ['accuracy'])
model.fit(padded_x, classes, epochs= 20, batch_size = 10)
print('\n Accuracy: %.4f' %(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6863 - accuracy: 0.8000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6839 - accuracy: 0.9000
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6815 - accuracy: 0.9000
Epoch 4/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6791 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6767 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6743 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6719 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6695 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6670 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6646 - accuracy: 0.9000
Epoch 11/20
1/1 [======================

In [73]:
emotion_list = []
for i in model.predict(padded_x):
  if i >0.5:
    emotion_list.append('Positive')
  else: emotion_list.append('Nagative')

for i in range(len(docs)):
  print(docs[i],':',emotion_list[i])

너무 재밌네요 : Positive
최고에요 : Positive
참 잘 만든 영화예요 : Positive
추천하고 싶은 영화입니다. : Positive
한번 더 보고 싶네요 : Positive
글쎄요 : Nagative
별로에요 : Nagative
생각보다 지루하네요 : Nagative
연기가 어색해요 : Nagative
재미없어요 : Nagative


## 5.이해결론
* 텍스트를 딥러닝 모델에 넣기 위해선? 토큰화 과정이 필요!
* ex) '난 참 멋있어' 는 토큰화하면 [[1,2,3]] 이 된다. 
* 여기서 각각의 숫자가, 단어를 토큰화 했을시의 인덱스 넘버! '난 : 1', '참 : 2', '멋있어 :3'
* 여기서, 각각의 토큰화했을때의 인덱스 넘버를 원-핫 인코딩을 해주어야 한다. 1 -> [0,1,0,0], 2 ->[0,0,1,0] ~~
* 하지만 여기서 '나도 멋있어'의 문장도 함께 딥러닝 모델의 입력으로 넣어주기위해선?
* 입력되는 인덱스 배열의 크기가 다르기 때문에! 이를 맞춰주는 padding과정을 거쳐주어야 한다!
* 따라서 위의 코딩을 순서화 하자면?
* 1. 주어진 문장들을(docs) 토크나이저를 통한 인덱스 배열로 변환.
* 2. 인덱스 배열들의 각각 길이를 맞추기 위한 padding작업
* 3. padding작업을 마친 후, 딥러닝 모델 설계 시 벡터의 크기를 맞춰줄 embedding layer 넣어주기 
* 4.임베딩 레이어에서, 입력은 토크나이저를 통한 각 문장을 구성하는 단어들의 인덱스(최대) +1, 출력은 각 단어를 구성하는 벡터를 맞춰줄 임의의 수, 
input_length는 패딩 작업을 거칠 때 맞춰준 각 단어의 인덱스 배열의 구성 수
* 5. fitting시, train_feature 로는 패딩된 인덱스배열, train_result는 사정에 정의된대로 알아서..